### ISSUE TITLE
--compress option is only supported by Tropico 5

### ISSUE THREAD

**Issue by nickelc** [iAmMutun/SurvivingMarsTH#3]
Hey, i saw you starred my repository :thumbsup:

You mentioned the --compress option in your readme but only Tropico 5 compresses the whole hpk files for its challenges. All other games should crash on startup or ignore the file.

**Comment by Thierthyn** [comment]
@nickelc Yep. Maybe he forgot to opt those options out but only his preset files worked out without compressing. Thanks for information as I'm dealing with some kind of localization framework to suggest him. I've been currently working on a hpk repacker tool.

**Comment by iAmMutun** [comment]
@nickelc Thanks for visiting us and for the info! Strange, it seems to work yesterday. I'm at work and can't test it again right now.

Anyhow, the reason we need to modify any hpk file at all is because the game doesn't include any Thai font with it, yet. I just contacted them yesterday and they had confirmed that there's a plan to add more fonts in the upcoming updates.

So, for now, this is all simply a temporary solution. The hpk files will be left alone when we get a Thai font in the game.
